WebColors = [
{ color: "ffffff", name: "White", name2: "Белый", presentation: "Белый (White)" },
{ color: "fffafa", name: "Snow", name2: "Белоснежный", presentation: "Белоснежный (Snow)" },
{ color: "f0fff0", name: "HoneyDew", name2: "Роса", presentation: "Роса (HoneyDew)" },
{ color: "f5fffa", name: "MintCream", name2: "МятныйКрем", presentation: "Мятный крем (MintCream)" },
{ color: "f0ffff", name: "Azure", name2: "Лазурный", presentation: "Лазурный (Azure)" },
{ color: "f0f8ff", name: "AliceBlue", name2: "АкварельноСиний", presentation: "Акварельно-синий (AliceBlue)" },
{ color: "f8f8ff", name: "GhostWhite", name2: "ПризрачноБелый", presentation: "Призрачно-белый (GhostWhite)" },
{ color: "f5f5f5", name: "WhiteSmoke", name2: "ДымчатоБелый", presentation: "Дымчато-белый (WhiteSmoke)" },
{ color: "fff5ee", name: "SeaShell", name2: "Перламутровый", presentation: "Перламутровый (SeaShell)" },
{ color: "f5f5dc", name: "Beige", name2: "Бежевый", presentation: "Бежевый (Beige)" },
{ color: "fdf5e6", name: "OldLace", name2: "СтароеКружево", presentation: "Старое кружево (OldLace)" },
{ color: "fffbf0", name: "Cream", name2: "Кремовый", presentation: "Кремовый (Cream)" },
{ color: "fffaf0", name: "FloralWhite", name2: "ЦветокБелый", presentation: "Цветок Белый (FloralWhite)" },
{ color: "fffff0", name: "Ivory", name2: "СлоноваяКость", presentation: "Слоновая Кость (Ivory)" },
{ color: "faebd7", name: "AntiqueWhite", name2: "АнтикБелый", presentation: "АнтикБелый (AntiqueWhite)" },
{ color: "faf0e6", name: "Linen", name2: "Льняной", presentation: "Льняной (Linen)" },
{ color: "fff0f5", name: "LavenderBlush", name2: "ГолубойСКраснымОттенком", presentation: "Голубой с красным оттенком (LavenderBlush)" },
{ color: "ffe4e1", name: "MistyRose", name2: "ТусклоРозовый", presentation: "Тускло-розовый (MistyRose)" },
{ color: "dcdcdc", name: "Gainsboro", name2: "СеребристоСерый", presentation: "Серебристо-серый (Gainsboro)" },
{ color: "c0c0c0", name: "LightGray", name2: "СветлоСерый", presentation: "Светло-серый (LightGray)" },
{ color: "c0c0c0", name: "Silver", name2: "Серебряный", presentation: "Серебряный (Silver)" },
{ color: "a9a9a9", name: "DarkGray", name2: "ТемноСерый", presentation: "Темно-серый (DarkGray)" },
{ color: "a0a0a4", name: "MediumGray", name2: "НейтральноСерый", presentation: "Нейтрально-серый (MediumGray)" },
{ color: "808080", name: "Gray", name2: "Серый", presentation: "Серый (Gray)" },
{ color: "696969", name: "DimGray", name2: "ТусклоСерый", presentation: "Тускло-серый (DimGray)" },
{ color: "778899", name: "LightSlateGray", name2: "СветлоГрифельноСерый", presentation: "Светло-грифельно-серый (LightSlateGray)" },
{ color: "708090", name: "SlateGray", name2: "ГрифельноСерый", presentation: "Грифельно-серый (SlateGray)" },
{ color: "2f4f4f", name: "DarkSlateGray", name2: "ТемноГрифельноСерый", presentation: "Темно-грифельно-серый (DarkSlateGray)" },
{ color: "000000", name: "Black", name2: "Черный", presentation: "Черный (Black)" },
{ color: "cd5c5c", name: "IndianRed", name2: "Киноварь", presentation: "Киноварь (IndianRed)" },
{ color: "f08080", name: "LightCoral", name2: "СветлоКоралловый", presentation: "Светло-коралловый (LightCoral)" },
{ color: "fa8072", name: "Salmon", name2: "Лосось", presentation: "Лосось (Salmon)" },
{ color: "e9967a", name: "DarkSalmon", name2: "ЛососьТемный", presentation: "Лосось Темный (DarkSalmon)" },
{ color: "ffa07a", name: "LightSalmon", name2: "ЛососьСветлый", presentation: "Лосось светлый (LightSalmon)" },
{ color: "dc143c", name: "Crimson", name2: "Малиновый", presentation: "Малиновый (Crimson)" },
{ color: "ff0000", name: "Red", name2: "Красный", presentation: "Красный (Red)" },
{ color: "b22222", name: "FireBrick", name2: "Кирпичный", presentation: "Кирпичный (FireBrick)" },
{ color: "8b0000", name: "DarkRed", name2: "ТемноКрасный", presentation: "Темно-красный (DarkRed)" },
{ color: "ffc0cb", name: "Pink", name2: "Розовый", presentation: "Розовый (Pink)" },
{ color: "ffb6c1", name: "LightPink", name2: "СветлоРозовый", presentation: "Светло-розовый (LightPink)" },
{ color: "ff69b4", name: "HotPink", name2: "ТеплоРозовый", presentation: "Тепло-розовый (HotPink)" },
{ color: "ff1493", name: "DeepPink", name2: "НасыщенноРозовый", presentation: "Насыщенно-розовый (DeepPink)" },
{ color: "c71585", name: "MediumVioletRed", name2: "НейтральноФиолетовоКрасный", presentation: "Нейтрально-фиолетово-красный (MediumVioletRed)" },
{ color: "d02090", name: "VioletRed", name2: "КрасноФиолетовый", presentation: "Красно-фиолетовый (VioletRed)" },
{ color: "db7093", name: "PaleVioletRed", name2: "БледноКрасноФиолетовый", presentation: "Бледно-красно-фиолетовый (PaleVioletRed)" },
{ color: "ff7f50", name: "Coral", name2: "Коралловый", presentation: "Коралловый (Coral)" },
{ color: "ff6347", name: "Tomato", name2: "Томатный", presentation: "Томатный (Tomato)" },
{ color: "ff4500", name: "OrangeRed", name2: "ОранжевоКрасный", presentation: "Оранжево-красный (OrangeRed)" },
{ color: "ff8c00", name: "DarkOrange", name2: "ТемноОранжевый", presentation: "Темно-оранжевый (DarkOrange)" },
{ color: "ffa500", name: "Orange", name2: "Оранжевый", presentation: "Оранжевый (Orange)" },
{ color: "ffd700", name: "Gold", name2: "Золотой", presentation: "Золотой (Gold)" },
{ color: "ffff00", name: "Yellow", name2: "Желтый", presentation: "Желтый (Yellow)" },
{ color: "ffffe0", name: "LightYellow", name2: "СветлоЖелтый", presentation: "Светло-желтый (LightYellow)" },
{ color: "fffacd", name: "LemonChiffon", name2: "Лимонный", presentation: "Лимонный (LemonChiffon)" },
{ color: "fafad2", name: "LightGoldenRodYellow", name2: "СветлоЖелтыйЗолотистый", presentation: "Светло-желтый золотистый (LightGoldenrodYellow)" },
{ color: "ffefd5", name: "PapayaWhip", name2: "ТопленоеМолоко", presentation: "Топленое молоко (PapayaWhip)" },
{ color: "ffe4b5", name: "Moccasin", name2: "ЗамшаСветлый", presentation: "Замша Светлый (Moccasin)" },
{ color: "ffdab9", name: "PeachPuff", name2: "Персиковый", presentation: "Персиковый (PeachPuff)" },
{ color: "eee8aa", name: "PaleGoldenrod", name2: "БледноЗолотистый", presentation: "Бледно-золотистый (PaleGoldenrod)" },
{ color: "f0e68c", name: "Khaki", name2: "Хаки", presentation: "Хаки (Khaki)" },
{ color: "bdb76b", name: "DarkKhaki", name2: "ХакиТемный", presentation: "Хаки Темный (DarkKhaki)" },
{ color: "e6e6fa", name: "Lavender", name2: "БледноЛиловый", presentation: "Бледно-лиловый (Lavender)" },
{ color: "d8bfd8", name: "Thistle", name2: "БледноСиреневый", presentation: "Бледно-сиреневый (Thistle)" },
{ color: "dda0dd", name: "Plum", name2: "Сливовый", presentation: "Сливовый (Plum)" },
{ color: "ee82ee", name: "Violet", name2: "Фиолетовый", presentation: "Фиолетовый (Violet)" },
{ color: "da70d6", name: "Orchid", name2: "Орхидея", presentation: "Орхидея (Orchid)" },
{ color: "ff00ff", name: "Fuchsia", name2: "Фуксия", presentation: "Фуксия (Fuchsia)" },
{ color: "ff00ff", name: "Magenta", name2: "Фуксин", presentation: "Фуксин (Magenta)" },
{ color: "ba55d3", name: "MediumOrchid", name2: "ОрхидеяНейтральный", presentation: "Орхидея Нейтральный (MediumOrchid)" },
{ color: "9370db", name: "MediumPurple", name2: "НейтральноПурпурный", presentation: "Нейтрально-пурпурный (MediumPurple)" },
{ color: "8a2be2", name: "BlueViolet", name2: "СинеФиолетовый", presentation: "Сине-фиолетовый (BlueViolet)" },
{ color: "9400d3", name: "DarkViolet", name2: "ТемноФиолетовый", presentation: "Темно-фиолетовый (DarkViolet)" },
{ color: "9932cc", name: "DarkOrchid", name2: "ОрхидеяТемный", presentation: "Орхидея Темный (DarkOrchid)" },
{ color: "8b008b", name: "DarkMagenta", name2: "ФуксинТемный", presentation: "Фуксин Темный (DarkMagenta)" },
{ color: "800080", name: "Purple", name2: "Пурпурный", presentation: "Пурпурный (Purple)" },
{ color: "4b0082", name: "Indigo", name2: "Индиго", presentation: "Индиго (Indigo)" },
{ color: "8470ff", name: "LightSlateBlue", name2: "СветлоГрифельноСиний", presentation: "Светло-грифельно-синий (LightSlateBlue)" },
{ color: "6a5acd", name: "SlateBlue", name2: "ГрифельноСиний", presentation: "Грифельно-синий (SlateBlue)" },
{ color: "483d8b", name: "DarkSlateBlue", name2: "ТемноГрифельноСиний", presentation: "Темно-грифельно-синий (DarkSlateBlue)" },
{ color: "7b68ee", name: "MediumSlateBlue", name2: "НейтральноГрифельноСиний", presentation: "Нейтрально-грифельно-синий (MediumSlateBlue)" },
{ color: "adff2f", name: "GreenYellow", name2: "ЗеленоЖелтый", presentation: "Зелено-желтый (GreenYellow)" },
{ color: "7fff00", name: "Chartreuse", name2: "ЗеленоватоЖелтый", presentation: "Зеленовато-желтый (Chartreuse)" },
{ color: "7cfc00", name: "LawnGreen", name2: "ЗеленаяЛужайка", presentation: "Зеленая лужайка (LawnGreen)" },
{ color: "00ff00", name: "Lime", name2: "ЗеленоватоЛимонный", presentation: "Зеленовато-лимонный (Lime)" },
{ color: "32cd32", name: "LimeGreen", name2: "ЛимонноЗеленый", presentation: "Лимонно-зеленый (LimeGreen)" },
{ color: "98fb98", name: "PaleGreen", name2: "БледноЗеленый", presentation: "Бледно-зеленый (PaleGreen)" },
{ color: "90ee90", name: "LightGreen", name2: "СветлоЗеленый", presentation: "Светло-зеленый (LightGreen)" },
{ color: "00fa9a", name: "MediumSpringGreen", name2: "НейтральноВесеннеЗеленый", presentation: "Нейтрально-весенне-зеленый (MediumSpringGreen)" },
{ color: "00ff7f", name: "SpringGreen", name2: "ВесеннеЗеленый", presentation: "Весенне-зеленый (SpringGreen)" },
{ color: "3cb371", name: "MediumSeaGreen", name2: "ЦветМорскойВолныНейтральный", presentation: "Цвет морской волны Нейтральный (MediumSeaGreen)" },
{ color: "2e8b57", name: "Seagreen", name2: "ЦветМорскойВолны", presentation: "Цвет морской волны (Seagreen)" },
{ color: "228b22", name: "ForestGreen", name2: "ЗеленыйЛес", presentation: "Зеленый лес (ForestGreen)" },
{ color: "008000", name: "Green", name2: "Зеленый", presentation: "Зеленый (Green)" },
{ color: "c0dcc0", name: "MediumGreen", name2: "НейтральноЗеленый", presentation: "Нейтрально-зеленый (MediumGreen)" },
{ color: "006400", name: "DarkGreen", name2: "ТемноЗеленый", presentation: "Темно-зеленый (DarkGreen)" },
{ color: "9acd32", name: "YellowGreen", name2: "ЖелтоЗеленый", presentation: "Желто-зеленый (YellowGreen)" },
{ color: "6b8e23", name: "Olivedrab", name2: "ТусклоОливковый", presentation: "Тускло-оливковый (OliveRab)" },
{ color: "808000", name: "Olive", name2: "Оливковый", presentation: "Оливковый (Olive)" },
{ color: "556b2f", name: "DarkOliveGreen", name2: "ТемноОливковоЗеленый", presentation: "Темно-оливково-зеленый (DarkOliveGreen)" },
{ color: "66cdaa", name: "MediumAquaMarine", name2: "НейтральноАквамариновый", presentation: "Нейтрально-аквамариновый (MediumAquaMarine)" },
{ color: "8fbc8b", name: "DarkSeaGreen", name2: "ЦветМорскойВолныТемный", presentation: "Цвет морской волны Темный (DarkSeaGreen)" },
{ color: "20b2aa", name: "LightSeaGreen", name2: "ЦветМорскойВолныСветлый", presentation: "Цвет морской волны Светлый (LightSeaGreen)" },
{ color: "008b8b", name: "DarkCyan", name2: "ЦианТемный", presentation: "Циан Темный (DarkCyan)" },
{ color: "008080", name: "Teal", name2: "ЦианНейтральный", presentation: "Циан Нейтральный (Teal)" },
{ color: "00ffff", name: "Aqua", name2: "ЦианАкварельный", presentation: "Циан акварельный (Aqua)" },
{ color: "00ffff", name: "Cyan", name2: "Циан", presentation: "Циан (Cyan)" },
{ color: "e0ffff", name: "LightCyan", name2: "ЦианСветлый", presentation: "Циан светлый (LightCyan)" },
{ color: "afeeee", name: "PaleTurquoise", name2: "БледноБирюзовый", presentation: "Бледно-бирюзовый (PaleTurquoise)" },
{ color: "7fffd4", name: "Aquamarine", name2: "Аквамарин", presentation: "Аквамарин (Aquamarine)" },
{ color: "40e0d0", name: "Turquoise", name2: "Бирюзовый", presentation: "Бирюзовый (Turquoise)" },
{ color: "48d1cc", name: "MediumTurquoise", name2: "НейтральноБирюзовый", presentation: "Нейтрально-бирюзовый (MediumTurquoise)" },
{ color: "00ced1", name: "DarkTurquoise", name2: "ТемноБирюзовый", presentation: "Темно-бирюзовый (DarkTurquoise)" },
{ color: "5f9ea0", name: "CadetBlue", name2: "СероСиний", presentation: "Серо-синий (CadetBlue)" },
{ color: "4682b4", name: "SteelBlue", name2: "СинийСоСтальнымОттенком", presentation: "Синий со стальным оттенком (SteelBlue)" },
{ color: "b0c4de", name: "LightSteelBlue", name2: "ГолубойСоСтальнымОттенком", presentation: "Голубой со стальным оттенком (LightSteelBlue)" },
{ color: "b0e0e6", name: "PowderBlue", name2: "СинийСПороховымОттенком", presentation: "Синий с пороховым оттенком (PowderBlue)" },
{ color: "a6caf0", name: "LightBlue", name2: "Голубой", presentation: "Голубой (LightBlue)" },
{ color: "87ceeb", name: "SkyBlue", name2: "НебесноГолубой", presentation: "Небесно-голубой (SkyBlue)" },
{ color: "87cefa", name: "LightSkyBlue", name2: "СветлоНебесноГолубой", presentation: "Светло-небесно-голубой (LightSkyBlue)" },
{ color: "00bfff", name: "DeepSkyBlue", name2: "НасыщенноНебесноГолубой", presentation: "Насыщенно-небесно-голубой (DeepSkyBlue)" },
{ color: "1e90ff", name: "DodgerBlue", name2: "СинеСерый", presentation: "Сине-серый (DodgerBlue)" },
{ color: "6495ed", name: "CornFlowerBlue", name2: "Васильковый", presentation: "Васильковый (CornFlowerBlue)" },
{ color: "4169e1", name: "RoyalBlue", name2: "КоролевскиГолубой", presentation: "Королевский Голубой (RoyalBlue)" },
{ color: "0000ff", name: "Blue", name2: "Синий", presentation: "Синий (Blue)" },
{ color: "0000cd", name: "MediumBlue", name2: "НейтральноСиний", presentation: "Нейтрально-синий (MediumBlue)" },
{ color: "00008b", name: "DarkBlue", name2: "ТемноСиний", presentation: "Темно-синий (DarkBlue)" },
{ color: "000080", name: "Navy", name2: "Ультрамарин", presentation: "Ультрамарин (Navy)" },
{ color: "191970", name: "MidnightBlue", name2: "ПолночноСиний", presentation: "Полночно-синий (MidnightBlue)" },
{ color: "fff8dc", name: "CornSilk", name2: "ШелковыйОттенок", presentation: "Шелковый оттенок (CornSilk)" },
{ color: "ffebcd", name: "BlanchedAlmond", name2: "БледноМиндальный", presentation: "Бледно-Миндальный (BlanchedAlmond)" },
{ color: "ffe4c4", name: "Bisque", name2: "СветлоКоричневый", presentation: "Светло-коричневый (Bisque)" },
{ color: "ffdead", name: "NavajoWhite", name2: "НавахоБелый", presentation: "Навахо Белый (NavajoWhite)" },
{ color: "f5deb3", name: "Wheat", name2: "Пшеничный", presentation: "Пшеничный (Wheat)" },
{ color: "deb887", name: "BurlyWood", name2: "Древесный", presentation: "Древесный (BurlyWood)" },
{ color: "d2b48c", name: "Tan", name2: "РыжеватоКоричневый", presentation: "Рыжевато-коричневый (Tan)" },
{ color: "bc8f8f", name: "RosyBrown", name2: "РозовоКоричневый", presentation: "Розово-коричневый (RosyBrown)" },
{ color: "f4a460", name: "SandyBrown", name2: "ПесочноКоричневый", presentation: "Песочно-коричневый (SandyBrown)" },
{ color: "ffec8b", name: "LightGoldenRod", name2: "СветлоЗолотистый", presentation: "Светло-золотистый (LightGoldenrod)" },
{ color: "daa520", name: "Goldenrod", name2: "Золотистый", presentation: "Золотистый (Goldenrod)" },
{ color: "b8860b", name: "DarkGoldenRod", name2: "ТемноЗолотистый", presentation: "Темно-золотистый (DarkGoldenRod)" },
{ color: "cd853f", name: "Peru", name2: "НейтральноКоричневый", presentation: "Нейтрально-коричневый (Peru)" },
{ color: "d2691e", name: "Chocolate", name2: "Шоколадный", presentation: "Шоколадный (Chocolate)" },
{ color: "8b4513", name: "SaddleBrown", name2: "КожаноКоричневый", presentation: "Кожано-коричневый (SaddleBrown)" },
{ color: "a0522d", name: "Sienna", name2: "Охра", presentation: "Охра (Sienna)" },
{ color: "a52a2a", name: "Brown", name2: "Коричневый", presentation: "Коричневый (Brown)" },
{ color: "800000", name: "Maroon", name2: "ТемноБордовый", presentation: "Темно-бордовый (Maroon)" }
];
